## Introduction


Motor commands, or the coordinated actions of our brains and nervous system, enable the muscular movement of daily life. As we age or suffer from an illness, the brain’s motor commands degenerate, leading to difficulty in mobility and communication. Thus, it is imperative to study motor commands and the neural system that facilitates movement in our bodies. Maybe a connecting sentence here --  probs mention action potenshy. In this proposal, we aim to create a Python package that decomposes and visualizes the electrical signals sent from our brains to various muscles.
Electromyography (EMG) is used to quantify the net electrical charge of a muscle as it contracts. In non-invasive electromyography, surface electrodes are placed on the skin and voltage is measured as participants flex and relax a muscle. The collected signal is the sum of all the electric action potential fired from neurons attached to a muscle fiber. A single muscle fiber, along with its connected motor neurons, is known as a motor unit. Typically, researchers are interested in discovering when and which motor unit contributed to the net EMG signal. 
Currently, the Sensorimotor Physiology Lab at UBC School of Kinesiology decomposes EMG signals using a free software from OT Bioelettronica, which parses the individual action potential spike trains using a closed-source algorithm. This proprietary decomposition algorithm is based off a paper published by Negro, et al (2016), which provides the mathmatical logic and pseudocode behind the algorithm. 
Talk about specifics here
Although we are now able to use surface muscle recordings, the free software used to decompose the individual components from the recorded net motor signals are insufficient for the needs of the UBC School of Kinesiology. The available free software is limited to recordings of 100 seconds or less and does not provide the opportunity to manually mark false positives in real time and learn from its mistakes. Our goal is to improve on the blind source separation (BSS) algorithm to enable both features. BSS involves separating the individual source signals from the net motor signals recorded with little to no information about each source signal.
The final data product we hope to deliver is a Python package that allows the user to decompose a set of non-invasive electromyography muscle recordings from a trial lasting roughly five minutes. The package will include a visualization component from which the user will be able to manually add filters the package will use to re-learn and update the outputs, avoiding previous false positive results.
The use of non-invasive methods to estimate the motor signals controlling our muscles will open the door to new opportunities to explore the mechanisms underlying our brain’s interactions with our muscles.
